# SPDX-License-Identifier: MIT-0
---
# Handlers with the same listen tag are executed in the order they are defined
- name: Check Apache config syntax
  listen:
    - Reload apache
    - Restart apache
  ansible.builtin.command:
    cmd: apachectl configtest
  changed_when: false

- name: Reload Apache service
  listen: Reload apache
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart Apache service
  listen: Restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
