---
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-instance
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    # --- Systemd requirements ---
    privileged: true                  # Required to run systemd/init as PID 1
    command: "/usr/lib/systemd/systemd" # The command to start systemd
    cgroupns_mode: host               # Necessary for cgroups v2 (modern Docker/OS)
    volumes:                          # Mount cgroups filesystem to satisfy systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
      roles_path: '$MOLECULE_PROJECT_DIRECTORY/../roles'
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
        - --inventory=/path/to/inventory.yml
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    cleanup: cleanup.yml
    prepare: prepare.yml
    side_effect: side_effect.yml
    verify: verify.yml

scenario:
  name: php
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
