---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure required testing utilities (logrotate) are installed
      ansible.builtin.package:
        name: logrotate
        state: present
        update_cache: true
        cache_valid_time: 3600
