# SPDX-License-Identifier: MIT-0
---
# This playbook tests the PHP upgrade scenario
# It upgrades from PHP 8.2 (installed in converge.yml) to PHP 8.4
# This validates the remove_old_version functionality

- name: Side Effect - Test PHP Upgrade
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    # Target PHP version for upgrade
    php_version: "8.4"

    # Old PHP version to remove (installed in converge.yml)
    php_old_version: "8.2"

  tasks:
    - name: Display upgrade information
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Testing PHP Upgrade Scenario"
          - "=========================================="
          - "Upgrading from PHP {{ php_old_version }} to {{ php_version }}"
          - "This will test the remove_old_version functionality"
          - "=========================================="

    - name: Apply php role for upgrade
      ansible.builtin.include_role:
        name: php
      tags:
        - remove_old_version
        - php_remove_old_version
        - install
        - php_install
        - configure_cli
        - php_configure_cli
        - set_default_cli_version
        - php_set_default_cli_version
        - php_install_mssql_extension
        - install_mssql_extension
        - logrotate_cli
        - php_logrotate_cli
        - configure_fpm
        - php_configure_fpm
        - logrotate_fpm
        - php_logrotate_fpm

    - name: Display upgrade completion
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "PHP Upgrade Completed"
          - "=========================================="
          - "Old version {{ php_old_version }} should be removed"
          - "New version {{ php_version }} should be active"
          - "Proceeding to verification tests..."
          - "=========================================="
