---
php_version: "8.2"
php_fpm_enabled: true
php_composer_enabled: true
php_cli_set_as_default_version: true
# php_status_page_enabled: true
# php_proxy_timeout: 60

# Apache PHP-FPM status proxy configuration
# apache_php_fpm_status_configs:
#   - version: "{{ php_version }}"
#     status_path: "{{ php_pool_settings.status_path }}"
#     ping_path: "{{ php_pool_settings.ping_path }}"
#     proxy_timeout: "{{ php_proxy_timeout }}"
#     allowed_hosts: []
php_packages:
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-curl"
php_cli_settings:
  short_open_tag:
    value: true
    type: bool
  memory_limit:
    value: "512M"
    type: string
  error_reporting:
    value: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
    type: string
  error_log:
    value: error.log
    type: path
  post_max_size:
    value: 256M
    type: size
php_fpm_settings:
  max_execution_time:
    value: 120
    type: int
  memory_limit:
    value: "1024M"
    type: string
  error_reporting:
    value: E_ALL & ~E_NOTICE & ~E_STRICT
    type: string
  error_log:
    value: /var/log/php8.2/php-fpm-error.log
    type: path
php_pool_settings:
  pool_name: test-pool
  pm: dynamic
  pm_max_children: 10
  pm_start_servers: 3
  pm_min_spare_servers: 2
  pm_max_spare_servers: 5
  status_path: /fpm-status
  ping_path: /fpm-ping
  ping_response: pong-test
php_pool_additional_settings:
  slowlog: /var/log/php/php-fpm-slow.log
  php_admin_value[error_log]: /var/log/php/pool-admin-error.log
  php_admin_flag[log_errors]: "on"
php_mssql_extension_enabled: true
php_mssql_package_version: 18
