# SPDX-License-Identifier: MIT-0
---
# This scenario tests the php-upgrade.yml playbook
# It validates that the playbook correctly upgrades PHP from one version to another

- name: Display upgrade test information
  hosts: all
  gather_facts: false
  tasks:
    - name: Show scenario details
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Testing: playbooks/php-upgrade.yml"
          - "=========================================="
          - "Upgrading from PHP {{ php_old_version }} to PHP {{ php_version }}"
          - "Expected outcome: Old version removed, new version installed"
          - "=========================================="

- name: Import PHP upgrade playbook
  ansible.builtin.import_playbook: ../../../playbooks/php-upgrade.yml

- name: Display test completion
  hosts: all
  gather_facts: false
  tasks:
    - name: Show completion message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Upgrade Playbook Execution Completed"
          - "=========================================="
          - "Next: verify.yml will validate the upgrade"
          - "=========================================="