---
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-instance
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    # --- Systemd requirements ---
    privileged: true                  # Required to run systemd/init as PID 1
    command: "/usr/lib/systemd/systemd" # The command to start systemd
    cgroupns_mode: host               # Necessary for cgroups v2 (modern Docker/OS)
    volumes:                          # Mount cgroups filesystem to satisfy systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      verbosity: 1
      roles_path: '$MOLECULE_PROJECT_DIRECTORY/../roles'
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
  inventory:
    host_vars:
      ${MOLECULE_SCENARIO_NAME}-instance:
        php_old_version: "8.1"
        php_version: "8.2"
        php_fpm_enabled: true
        php_cli_set_as_default_version: true
        php_cli_logrotate_enabled: true
        php_fpm_logrotate_enabled: true
        php_skip_confirm: true

scenario:
  name: php-playbook-upgrade
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible