# SPDX-License-Identifier: MIT-0
---
# Prepare installs the old PHP version
# This sets up the starting state for the upgrade test
- name: Prepare environment with old PHP version
  hosts: php
  gather_facts: true
  tasks:
    - name: Ensure required testing utilities (logrotate) are installed
      ansible.builtin.package:
        name: logrotate
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Install old PHP version
  import_playbook: ../../../playbooks/php-install.yml
  vars:
    php_version: "8.3"
    # php_version_old is used as the target version for the install playbook,
    # so we clear it here to avoid conflicts with the upgrade playbook's variables.
    php_old_version: ""
