# SPDX-License-Identifier: MIT-0
---
- name: Prepare test environment
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

    - name: Display environment information
      ansible.builtin.debug:
        msg:
          - "Test Environment:"
          - "  OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "  Architecture: {{ ansible_architecture }}"
          - "  PHP Version to Install: {{ php_version }}"