all:
  children:
    certificates_standalone_test:
      vars:
        # Test Let's Encrypt with standalone and nginx plugins
        certificates_mode: letsencrypt
        certificates_certbot_email: "test@example.com"
        certificates_certbot_mode: staging
        # Override ACME server to use Pebble
        certificates_acme_server: "https://pebble:14000/dir"
        # Disable SSL verification for Pebble's self-signed certificate
        certificates_acme_verify_ssl: false
        certificates_list:
          # HTTP-01 with standalone plugin
          - name: test-standalone-letsencrypt.example.com
            domains:
              - test-standalone-letsencrypt.example.com
              - www.test-standalone-letsencrypt.example.com
            challenge_type: http-01
            plugin: standalone

          # HTTP-01 with nginx plugin
          - name: test-nginx-letsencrypt.example.com
            domains:
              - test-nginx-letsencrypt.example.com
              - www.test-nginx-letsencrypt.example.com
            challenge_type: http-01
            plugin: nginx
