all:
  children:
    certificates_test:
      vars:
        # Test self-signed certificate generation
        certificates_mode: selfsigned
        certificates_list:
          # Basic self-signed certificate
          - name: test-basic.local
            common_name: test-basic.local
            organization: "Test Organization"
            days: 365

          # Advanced self-signed certificate with all fields
          - name: test-advanced.local
            common_name: test-advanced.local
            organization: "Advanced Test Org"
            organizational_unit: "IT Department"
            country: "US"
            state: "California"
            locality: "San Francisco"
            email: "test@example.com"
            days: 730
            key_size: 4096

          # Certificate with Subject Alternative Names
          - name: test-san.local
            common_name: test-san.local
            organization: "SAN Test Org"
            days: 365
            san:
              - DNS:www.test-san.local
              - DNS:api.test-san.local
              - DNS:mail.test-san.local
              - IP:192.168.1.100
              - IP:10.0.0.1

          # Multiple domain certificate
          - name: test-multidomain.local
            common_name: test-multidomain.local
            organization: "Multi-Domain Test"
            days: 365
            san:
              - DNS:test-multidomain.local
              - DNS:www.test-multidomain.local
              - DNS:*.test-multidomain.local

        # Default values to test
        certificates_default_days: 365
        certificates_default_key_size: 4096
        certificates_cert_dir: /etc/ssl/certs
        certificates_key_dir: /etc/ssl/private
        certificates_cert_mode: "0644"
        certificates_key_mode: "0600"
        certificates_owner: root
        certificates_group: root