---
all:
  hosts:
    certificates-instance:
      ansible_connection: docker
      # Certbot configuration for Pebble
      certificates_certbot_environment: test
      certificates_certbot_server_url: https://pebble:14000/dir
      certificates_certbot_email: test@example.com

      certificates_items:
        # ========================================
        # Self-Signed Certificates
        # ========================================

        # Use Case 1.1: Auto-detection for local TLD
        - name: autodetect.test

        # Use Case 1.2: Explicit self-signed with custom config (san)
        - name: custom.local
          mode: selfsigned
          country: US
          state: Texas
          locality: Austin
          organization: Test Corp
          organizational_unit: DevOps
          email: test@custom.local
          key_size: 2048
          validity_days: 730
          san:
            - DNS:custom.local
            - "DNS:*.custom.local"
            - IP:127.0.0.1

        # Use Case 1.3: Using global defaults
        - name: defaults.test
          mode: selfsigned

        # Use Case 1.4: SANs test
        - name: sans.test
          mode: selfsigned
          san:
            - DNS:alt.test
            - DNS:www.alt.test
            - IP:127.0.0.1
            - IP:192.168.1.1

        # Use Case 1.5: Import existing certificate
        - name: imported.test
          mode: imported
          src_cert: /tmp/import-certs/imported.test.crt
          src_key: /tmp/import-certs/imported.test.key
          src_chain: /tmp/import-certs/imported.test.chain.crt

        # ========================================
        # Let's Encrypt Certificates (Pebble)
        # ========================================

        # Use Case 2.1: Auto-detection for public TLD
        - name: autodetect.com

        # Use Case 2.2: HTTP-01 challenge with webroot
        - name: http01.example.com
          mode: letsencrypt
          challenge_type: http-01
          webroot: /var/www/html
          san:
            - www.http01.example.com

        # Use Case 2.3: DNS-01 challenge with custom provider
        - name: dns01.example.com
          mode: letsencrypt
          challenge_type: dns-01
          dns_provider: custom
          auth_hook: /usr/local/bin/authenticator.sh
          cleanup_hook: /usr/local/bin/cleanup.sh
          san:
            - "*.dns01.example.com"

  children:
    certificates_test:
      hosts:
        certificates-instance:
