---
- name: Configure logrotate for PHP FPM
  ansible.builtin.template:
    src: logrotate_fpm.conf.j2
    dest: /etc/logrotate.d/php{{ php_version }}-fpm
    owner: root
    group: root
    mode: '0644'
