# SPDX-License-Identifier: MIT-0
---
- name: Verify PHP {{ php_version }} binaries exist
  ansible.builtin.stat:
    path: "/usr/bin/php{{ php_version }}"
  register: php_binary_check
  failed_when: not php_binary_check.stat.exists

- name: Check current default PHP CLI version
  ansible.builtin.command: php --version
  register: php_current_version
  changed_when: false
  failed_when: false

- name: Set all PHP {{ php_version }} CLI tools as default
  community.general.alternatives:
    name: "{{ item }}"
    path: "/usr/bin/{{ item }}{{ php_version }}"
    priority: "{{ php_priority }}"
  loop:
    - php
    - phar
    - phar.phar
    - phpize
    - php-config
  when: >
    php_cli_set_as_default_version and
    (php_current_version.stdout is not defined or
     php_version not in php_current_version.stdout)
  tags:
    - php_set_cli_version
    - php_version_management