all:
  children:
    php:
      vars:
        php_version: "8.4"
        php_fpm_enabled: true
        php_cli_set_as_default_version: true
        php_cli_logrotate_enabled: true
        php_fpm_logrotate_enabled: true
        php_old_version: "8.3"
        php_packages:
          - "php{{ php_version }}-cli"
          - "php{{ php_version }}-bcmath"
          - "php{{ php_version }}-curl"
          - "php{{ php_version }}-dev"
          - "php{{ php_version }}-gd"
          - "php{{ php_version }}-imagick"
          - "php{{ php_version }}-imap"
          - "php{{ php_version }}-intl"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-opcache"
          - "php{{ php_version }}-xml"
          - "php{{ php_version }}-zip"
