# SPDX-License-Identifier: MIT-0
---
# ============================================================================
# PHP Version Configuration
# ============================================================================

# PHP version to install and configure.
# Specifies the major and minor version (e.g., 8.3, 8.4).
# Type: String
php_version: "8.4"

# ============================================================================
# Package Installation
# ============================================================================

# List of PHP packages to install from the Ondrej PHP PPA repository.
# This includes the main PHP package, CLI, and any extensions you need.
# Uncomment or add extensions based on your application requirements.
# Type: List of Strings
php_packages:
  - "php{{ php_version }}-cli"
  # - "php{{ php_version }}-bcmath"
  # - "php{{ php_version }}-curl"
  # - "php{{ php_version }}-dev"
  # - "php{{ php_version }}-gd"
  # - "php{{ php_version }}-imagick"
  # - "php{{ php_version }}-imap"
  # - "php{{ php_version }}-intl"
  # - "php{{ php_version }}-mbstring"
  # - "php{{ php_version }}-mysql"
  # - "php{{ php_version }}-opcache"
  # - "php{{ php_version }}-xml"
  # - "php{{ php_version }}-zip"

# ============================================================================
# Composer Configuration
# ============================================================================

# Enable Composer installation.
# Composer is the dependency manager for PHP.
# Type: Boolean
php_composer_enabled: false

# ============================================================================
# Version Management
# ============================================================================

# Determines if the newly installed PHP version should be set as the default CLI version.
# When enabled, the PHP version specified in `php_version` will become the system default
# for command-line PHP execution (updates /usr/bin/php symlink).
#
# This is useful when:
# - Installing PHP for the first time
# - Upgrading to a newer PHP version
# - Managing multiple PHP versions and wanting to switch the default
#
# Note: This uses the Debian alternatives system to manage version priority.
# Higher versions automatically receive higher priority.
#
# Type: Boolean
php_cli_set_as_default_version: true

# # Determines if the newly installed PHP-FPM version should be configured as the default
# # for web server integration. When enabled, sets the PHP_VERSION environment variable
# # in the web server configuration.
# #
# # This is useful when:
# # - Using PHP-FPM with a web server (Apache/Nginx)
# # - Running multiple PHP-FPM versions and needing to specify which one to use
# # - Ensuring the web server knows which PHP version to proxy requests to
# #
# # Requires:
# # - php_fpm_enabled: true
# # - php_web_server: must be set to 'apache' or 'nginx'
# #
# # Type: Boolean
# php_fpm_set_as_default_version: false

# # Specifies the web server being used with PHP-FPM for environment variable configuration.
# # Currently supported values: 'apache', 'nginx'
# #
# # When set to 'apache': Updates /etc/apache2/envvars with PHP_VERSION
# # When set to 'nginx': Updates /etc/default/php{version}-fpm with PHP_VERSION
# #
# # Type: String (Options: apache, nginx)
# php_web_server: "apache"

# Previous PHP version to remove during version upgrades or migrations.
# When defined, triggers complete cleanup of the old PHP installation including:
# - PHP packages and extensions
# - PHP-FPM service (stopped and disabled)
# - Configuration files
# - Logrotate configuration files
# - Alternatives system entries
#
# Safety measures:
# - Must be different from php_version (cannot remove the version being installed)
# - Removal only occurs when this variable is explicitly defined and non-empty
# - Supports clean migration between major or minor PHP versions
#
# Example: When upgrading from PHP 8.3 to 8.4, set php_old_version: "8.3"
#
# Type: String
php_old_version: ""

# Enable or disable the installation and configuration of Microsoft SQL Server drivers for PHP.
# Type: Boolean
php_mssql_extension_enabled: false

# Version of the Microsoft SQL Server driver for PHP to be installed.
# This is used when `php_mssql_extension_enabled` is set to true.
# Type: Integer
php_mssql_package_version: 18

# Settings for the `php.ini` configuration file for PHP-CLI.
# These settings customize PHP's behavior such as memory limits, error reporting, and file upload sizes.
# Each setting includes:
# - value: The value to set for this PHP configuration directive
# - type: The data type used for regex pattern matching (bool, int, size, string, path)
# Type: Dictionary
# NOTE: max_execution_time is hardcoded to 0 for the CLI SAPI so it is not configurable here.
php_cli_settings:
  short_open_tag:                         # Allow the use of short PHP tags.
    value: false
    type: bool
  max_input_time:                         # Maximum amount of time each script may spend parsing request data.
    value: 60
    type: int
  max_input_vars:                         # Maximum number of input variables that can be accepted.
    value: 1000
    type: int
  memory_limit:                           # Maximum amount of memory a script may consume.
    value: -1
    type: string
  error_reporting:                        # Error reporting level.
    value: E_ALL & ~E_DEPRECATED
    type: string
  display_errors:                         # Display errors in output.
    value: false
    type: bool
  display_startup_errors:                 # Display PHP startup errors.
    value: false
    type: bool
  ignore_repeated_errors:                 # Do not log repeated messages.
    value: false
    type: bool
  ignore_repeated_source:                 # Do not log repeated errors from the same source.
    value: false
    type: bool
  html_errors:                            # Disable HTML formatting in error messages.
    value: true
    type: bool
  error_log:                              # Path to the error log file.
    value: /var/log/php/php_errors.log
    type: path
  post_max_size:                          # Maximum size of POST data that PHP will accept.
    value: 8M
    type: size
  upload_max_filesize:                    # Maximum allowed size for uploaded files.
    value: 2M
    type: size
  max_file_uploads:                       # Maximum number of files that can be uploaded via a single request.
    value: 20
    type: int
  mail_add_x_header:                      # Add X-PHP-Originating-Script header to mail.
    value: false
    type: bool

# ============================================================================
# PHP-FPM Configuration
# ============================================================================

# Enable PHP-FPM installation and configuration.
# PHP-FPM is required for serving PHP applications via web servers.
# Type: Boolean
php_fpm_enabled: false

# Settings for the `php.ini` configuration file for PHP-FPM.
# These settings customize PHP's behavior such as memory limits, error reporting, and file upload sizes.
# Each setting includes:
# - value: The value to set for this PHP configuration directive
# - type: The data type used for regex pattern matching (bool, int, size, string, path)
# Type: Dictionary
php_fpm_settings:
  short_open_tag:                         # Allow the use of short PHP tags.
    value: false
    type: bool
  max_execution_time:                     # Maximum execution time of each script, in seconds.
    value: 30
    type: int
  max_input_time:                         # Maximum amount of time each script may spend parsing request data.
    value: 60
    type: int
  max_input_vars:                         # Maximum number of input variables that can be accepted.
    value: 1000
    type: int
  memory_limit:                           # Maximum amount of memory a script may consume.
    value: -1
    type: string
  error_reporting:                        # Error reporting level.
    value: E_ALL & ~E_DEPRECATED
    type: string
  display_errors:                         # Display errors in output.
    value: false
    type: bool
  display_startup_errors:                 # Display PHP startup errors.
    value: false
    type: bool
  ignore_repeated_errors:                 # Do not log repeated messages.
    value: false
    type: bool
  ignore_repeated_source:                 # Do not log repeated errors from the same source.
    value: false
    type: bool
  html_errors:                            # Disable HTML formatting in error messages.
    value: true
    type: bool
  error_log:                              # Path to the error log file.
    value: /var/log/php/php_errors.log
    type: path
  post_max_size:                          # Maximum size of POST data that PHP will accept.
    value: 8M
    type: size
  upload_max_filesize:                    # Maximum allowed size for uploaded files.
    value: 2M
    type: size
  max_file_uploads:                       # Maximum number of files that can be uploaded via a single request.
    value: 20
    type: int
  mail_add_x_header:                      # Add X-PHP-Originating-Script header to mail.
    value: false
    type: bool

# Configuration settings for PHP-FPM pools.
# This defines how PHP-FPM should manage its child processes.
# Each setting includes:
# - pool_name: The name of the pool (optional, defaults to www-{version})
# - pm: Process manager type (static, dynamic, ondemand)
# - pm_max_children: Maximum number of child processes
# - pm_start_servers: Number of child processes created on startup (dynamic only)
# - pm_min_spare_servers: Minimum number of spare idle processes (dynamic only)
# - pm_max_spare_servers: Maximum number of spare idle processes (dynamic only)
# - status_path: URI path for the FPM status page (optional)
# - ping_path: URI path for the FPM ping endpoint (optional)
# - ping_response: Response text for ping requests (optional)
# Type: Dictionary
php_pool_settings:
  pool_name: www
  pm: dynamic
  pm_max_children: 5
  pm_start_servers: 2
  pm_min_spare_servers: 1
  pm_max_spare_servers: 3
  status_path: /status
  ping_path: /ping
  ping_response: pong

# Enable PHP-FPM status page configuration.
# When enabled, the status page will be configured in the pool and accessible via web server.
# Type: Boolean
php_status_page_enabled: false

# Additional PHP-FPM pool configuration settings.
# This dictionary allows you to add any custom pool configuration directives dynamically.
# The key is the directive name and the value is the directive value.
# Common examples include:
# - slowlog: Path to the slow request log file
# - request_slowlog_timeout: Timeout for logging slow requests (e.g., "5s")
# - request_terminate_timeout: Timeout for terminating requests (e.g., "30s")
# - php_admin_value[error_log]: Override error_log for this pool
# - php_admin_value[memory_limit]: Override memory_limit for this pool
# - php_admin_flag[display_errors]: Override display_errors for this pool
# - catch_workers_output: Capture worker stdout/stderr (yes/no)
# - rlimit_files: Open file descriptor limit
# - rlimit_core: Core size limit
# - chdir: Change directory on startup
# - security.limit_extensions: Limit allowed file extensions
# Type: Dictionary
php_pool_additional_settings:
#   slowlog: /var/log/php/php{{ php_version }}-fpm-slow.log
#   request_slowlog_timeout: 5s
#   request_terminate_timeout: 30s
#   php_admin_value[error_log]: /var/log/php/pool-error.log
#   php_admin_value[memory_limit]: 256M
#   php_admin_flag[display_errors]: off
#   catch_workers_output: yes

# # Timeout value for proxying requests to PHP-FPM.
# # Type: Integer
# php_proxy_timeout: 60

# # List of hosts allowed to access the PHP-FPM status page.
# # Each entry includes an IP address and a comment describing its purpose.
# # Type: List of Dictionaries
# php_status_page_allowed_hosts: []
# #   - ip: 10.0.0.1
# #     comment: allow access to host

# ============================================================================
# Logrotate Configuration
# ============================================================================

# Enable logrotate for PHP CLI.
# Type: Boolean
php_cli_logrotate_enabled: false

# Path to the PHP CLI log file for log rotation.
# Type: String
php_cli_logrotate_path: "{{ php_cli_settings.error_log.value }}"

# Options for logrotate.
# Type: List of Strings
php_cli_logrotate_options:
  - su root root
  - daily
  - rotate 7
  - missingok
  - notifempty
  - compress
  - delaycompress

# Enable logrotate for PHP FPM.
# Type: Boolean
php_fpm_logrotate_enabled: false

# Path to the PHP FPM log file for log rotation.
# Type: String
php_fpm_logrotate_path: "{{ php_fpm_settings.error_log.value }}"

# Options for logrotate.
# Type: List of Strings
php_fpm_logrotate_options:
  - su root root
  - daily
  - rotate 7
  - missingok
  - notifempty
  - compress
  - delaycompress
