# SPDX-License-Identifier: MIT-0
---
# ============================================================================
# PHP Version Configuration
# ============================================================================

# Specifies the PHP version to install and configure.
# It defines the major and minor version (e.g., "8.3", "8.4").
# Type: String
php_version: "8.4"

# ============================================================================
# Package Installation
# ============================================================================

# Defines the list of PHP packages to install from the Ondrej PHP PPA repository.
# This should include the main PHP package, CLI, and any required extensions.
# Type: List of Strings
php_packages:
  - "php{{ php_version }}-cli"
  # - "php{{ php_version }}-bcmath"
  # - "php{{ php_version }}-curl"
  # - "php{{ php_version }}-dev"
  # - "php{{ php_version }}-gd"
  # - "php{{ php_version }}-imagick"
  # - "php{{ php_version }}-imap"
  # - "php{{ php_version }}-intl"
  # - "php{{ php_version }}-mbstring"
  # - "php{{ php_version }}-mysql"
  # - "php{{ php_version }}-opcache"
  # - "php{{ php_version }}-xml"
  # - "php{{ php_version }}-zip"

# ============================================================================
# Composer Configuration
# ============================================================================

# Determines whether to install Composer, the dependency manager for PHP.
# Type: Boolean
php_composer_enabled: false

# ============================================================================
# Version Management
# ============================================================================

# Determines if the newly installed PHP version should be set as the default for the CLI.
# If true, the version in `php_version` becomes the system-wide default for `php`.
# This is managed using the Debian alternatives system.
#
# Type: Boolean
php_cli_set_as_default_version: true

# A dictionary of settings for the `php.ini` configuration file for the PHP CLI.
# These settings customize PHP's behavior for command-line execution.
# Each setting is a dictionary with `value` and `type` keys.
#
# - `value`: The value for the PHP directive.
# - `type`: The data type for regex matching (bool, int, size, string, path).
#
# Note: `max_execution_time` is hardcoded to 0 for the CLI and is not configurable here.
#
# Type: Dictionary
php_cli_settings:
  short_open_tag:                         # Allow the use of short PHP tags.
    value: false
    type: bool
  max_input_time:                         # Maximum amount of time each script may spend parsing request data.
    value: 60
    type: int
  max_input_vars:                         # Maximum number of input variables that can be accepted.
    value: 1000
    type: int
  memory_limit:                           # Maximum amount of memory a script may consume.
    value: "-1"
    type: string
  error_reporting:                        # Error reporting level.
    value: E_ALL & ~E_DEPRECATED
    type: string
  display_errors:                         # Display errors in output.
    value: false
    type: bool
  display_startup_errors:                 # Display PHP startup errors.
    value: false
    type: bool
  ignore_repeated_errors:                 # Do not log repeated messages.
    value: false
    type: bool
  ignore_repeated_source:                 # Do not log repeated errors from the same source.
    value: false
    type: bool
  html_errors:                            # Disable HTML formatting in error messages.
    value: true
    type: bool
  error_log:                              # Path to the error log file.
    value: /var/log/php/php_errors.log
    type: path
  post_max_size:                          # Maximum size of POST data that PHP will accept.
    value: 8M
    type: size
  upload_max_filesize:                    # Maximum allowed size for uploaded files.
    value: 2M
    type: size
  max_file_uploads:                       # Maximum number of files that can be uploaded via a single request.
    value: 20
    type: int
  mail_add_x_header:                      # Add X-PHP-Originating-Script header to mail.
    value: false
    type: bool

# Determines whether to install and configure Microsoft SQL Server drivers for PHP.
# Type: Boolean
php_mssql_extension_enabled: false

# Specifies the version of the Microsoft SQL Server driver for PHP to install.
# This is only used if `php_mssql_extension_enabled` is true.
# Type: Integer
php_mssql_package_version: 18

# Specifies the previous PHP version to remove during an upgrade or migration.
# When defined, this triggers a complete cleanup of the old PHP installation,
# including packages, services, and configuration files.
#
# This must be different from `php_version`.
#
# Example: To upgrade from PHP 8.3 to 8.4, set `php_old_version: "8.3"`.
#
# Type: String
php_old_version: ""

# ============================================================================
# PHP-FPM Configuration
# ============================================================================

# Determines whether to install and configure PHP-FPM.
# PHP-FPM is required for serving PHP applications with a web server.
# Type: Boolean
php_fpm_enabled: false

# A dictionary of settings for the `php.ini` configuration file for PHP-FPM.
# These settings customize PHP's behavior for web requests.
# Each setting is a dictionary with `value` and `type` keys.
#
# - `value`: The value for the PHP directive.
# - `type`: The data type for regex matching (bool, int, size, string, path).
#
# Type: Dictionary
php_fpm_settings:
  short_open_tag:                         # Allow the use of short PHP tags.
    value: false
    type: bool
  max_execution_time:                     # Maximum execution time of each script, in seconds.
    value: 30
    type: int
  max_input_time:                         # Maximum amount of time each script may spend parsing request data.
    value: 60
    type: int
  max_input_vars:                         # Maximum number of input variables that can be accepted.
    value: 1000
    type: int
  memory_limit:                           # Maximum amount of memory a script may consume.
    value: "-1"
    type: string
  error_reporting:                        # Error reporting level.
    value: E_ALL & ~E_DEPRECATED
    type: string
  display_errors:                         # Display errors in output.
    value: false
    type: bool
  display_startup_errors:                 # Display PHP startup errors.
    value: false
    type: bool
  ignore_repeated_errors:                 # Do not log repeated messages.
    value: false
    type: bool
  ignore_repeated_source:                 # Do not log repeated errors from the same source.
    value: false
    type: bool
  html_errors:                            # Disable HTML formatting in error messages.
    value: true
    type: bool
  error_log:                              # Path to the error log file.
    value: /var/log/php/php_errors.log
    type: path
  post_max_size:                          # Maximum size of POST data that PHP will accept.
    value: 8M
    type: size
  upload_max_filesize:                    # Maximum allowed size for uploaded files.
    value: 2M
    type: size
  max_file_uploads:                       # Maximum number of files that can be uploaded via a single request.
    value: 20
    type: int
  mail_add_x_header:                      # Add X-PHP-Originating-Script header to mail.
    value: false
    type: bool

# A dictionary of additional custom settings for the PHP-FPM pool.
# This allows for advanced configuration of the FPM pool.
#
# Example:
# php_pool_additional_settings:
#   slowlog: /var/log/php/php{{ php_version }}-fpm-slow.log
#   request_slowlog_timeout: 5s
#
# Type: Dictionary
php_pool_additional_settings: {}
#   slowlog: /var/log/php/php{{ php_version }}-fpm-slow.log
#   request_slowlog_timeout: 5s
#   request_terminate_timeout: 30s
#   php_admin_value[error_log]: /var/log/php/pool-error.log
#   php_admin_value[memory_limit]: 256M
#   php_admin_flag[display_errors]: off
#   catch_workers_output: yes

# A dictionary of configuration settings for the PHP-FPM pool.
# This defines how PHP-FPM manages its child processes.
#
# Type: Dictionary
php_pool_settings:
  pool_name: www            # The name of the pool (optional, defaults to www-{version})
  pm: dynamic               # Process manager (static, dynamic, or ondemand)
  pm_max_children: 5        # Maximum number of child processes
  pm_start_servers: 2       # Number of child processes created on startup (dynamic only)
  pm_min_spare_servers: 1   # Minimum number of spare idle processes (dynamic only)
  pm_max_spare_servers: 3   # Maximum number of spare idle processes (dynamic only)
  status_path: /status      # URI path for the FPM status page (optional)
  ping_path: /ping          # URI path for the FPM ping endpoint (optional)
  ping_response: pong       # Response text for ping requests (optional)

# Determines whether to enable the PHP-FPM status page.
# If true, the status page will be configured and accessible via the web server.
# Type: Boolean
php_status_page_enabled: false

# ============================================================================
# Logrotate Configuration
# ============================================================================

# Determines whether to enable log rotation for the PHP CLI error log.
# Type: Boolean
php_cli_logrotate_enabled: false

# A list of options for logrotate for the PHP CLI log file.
#
# Type: List of Strings
php_cli_logrotate_options:
  - su root root
  - daily
  - rotate 7
  - missingok
  - notifempty
  - compress
  - delaycompress

# The path to the PHP CLI log file for log rotation.
# Type: String
php_cli_logrotate_path: "{{ php_cli_settings.error_log.value }}"

# Determines whether to enable log rotation for the PHP-FPM error log.
# Type: Boolean
php_fpm_logrotate_enabled: false

# A list of options for logrotate for the PHP-FPM log file.
#
# Type: List of Strings
php_fpm_logrotate_options:
  - su root root
  - daily
  - rotate 7
  - missingok
  - notifempty
  - compress
  - delaycompress

# The path to the PHP-FPM log file for log rotation.
# Type: String
php_fpm_logrotate_path: "{{ php_fpm_settings.error_log.value }}"
